# Register Algorithms here.
from .xql import XQL
from .redq import REDQ
from .cql import CQL
from .d4 import D4
from .td3 import TD3
from .sac import SAC
from .gumbel_sac import GumbelSAC
from .gumbel_td3 import GumbelTD3
